export const CREATE_PAYMENT_REQUEST = " CREATE_PAYMENT_REQUEST";
export const CREATE_PAYMENT_SUCCESS = " CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAIL = " CREATE_PAYMENT_FAIL";

export const PAYMENT_URL_REQUEST = " PAYMENT_URL_REQUEST";
export const PAYMENT_URL_SUCCESS = " PAYMENT_URL_SUCCESS";
export const PAYMENT_URL_FAIL = " PAYMENT_URL_FAIL";
